
import { HelpCircle, ChevronDown, ChevronUp, ShieldQuestion, Wallet, TrendingUp, Lock, Zap } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "FAQ | CrownEdge Broker Security & Support",
    description: "Find answers to frequently asked questions about CrownEdge Broker trading platform, account security, withdrawals, and institutional AI trading.",
};

export default function FAQPage() {
    const faqs = [
        {
            category: "General Information",
            questions: [
                {
                    q: "What is CrownEdge Broker?",
                    a: "CrownEdge Broker is an institutional-grade multi-asset investment platform established in 2014. We provide elite traders with access to Forex, Crypto, and Stock markets using proprietary AI execution technology."
                },
                {
                    q: "Is CrownEdge Broker a regulated platform?",
                    a: "Yes, CrownEdge Broker operates under strict compliance with global AML (Anti-Money Laundering) and KYC (Know Your Customer) protocols. We are regulated across multiple jurisdictions to ensure the highest level of investor protection."
                },
                {
                    q: "Where is CrownEdge headquartered?",
                    a: "Our global headquarters is located in London, United Kingdom, with regional operational hubs serving clients in over 120 countries."
                }
            ]
        },
        {
            category: "Trading & AI Technology",
            questions: [
                {
                    q: "How does the AI Trading system work?",
                    a: "Our proprietary AI Master Engine scans over 5,000 data points per second across global exchanges. It identifies surgical entry and exit points, managing risk automatically to ensure consistent profitability for all account tiers."
                },
                {
                    q: "Can I trade manually or is it only AI?",
                    a: "While our AI provides an automated edge, professional traders can also execute trades manually through our high-speed Trading Terminal with sub-5ms latency."
                },
                {
                    q: "What assets can I trade?",
                    a: "You can trade Bitcoin, Ethereum, and major cryptocurrencies, over 50 Forex pairs (including EUR/USD, GBP/JPY), global stocks, and commodities."
                }
            ]
        },
        {
            category: "Funding & Withdrawals",
            questions: [
                {
                    q: "How do I deposit funds?",
                    a: "You can fund your account via Bitcoin (BTC), Ethereum (ETH), USDT, Bank Wire Transfer, or Pix. Deposits are credited instantly after network verification."
                },
                {
                    q: "What is the Withdrawal Code/PIN?",
                    a: "For institutional security, all withdrawals require a unique Withdrawal Code generated by your account manager. This prevents unauthorized access even if your account credentials are compromised."
                },
                {
                    q: "How long do withdrawals take?",
                    a: "Withdrawals are processed within 2-24 hours depending on the asset class and your account tier. High-tier institutional accounts enjoy immediate priority processing."
                }
            ]
        },
        {
            category: "Security & Verification",
            questions: [
                {
                    q: "What is the KYC process?",
                    a: "To maintain compliance, users must verify their identity by uploading a government-issued ID (Front and Back) and a verification selfie. This ensures your account remains secure and fully functional."
                },
                {
                    q: "Are my funds safe?",
                    a: "Absolutely. We utilize institutional-grade cold storage for digital assets and keep fiat funds in segregated Tier-1 bank accounts, separate from company operating capital."
                }
            ]
        }
    ];

    return (
        <div className="min-h-screen bg-[#05070a] text-white">
            <Navbar />

            {/* FAQ Hero */}
            <section className="relative pt-40 pb-20 overflow-hidden">
                <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-brand-gold/5 blur-[150px] -z-10 rounded-full" />
                <div className="max-w-7xl mx-auto px-6 text-center">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand-gold/10 border border-brand-gold/20 text-brand-gold text-[10px] font-black tracking-widest uppercase mb-6">
                        <HelpCircle size={14} />
                        <span>Support Center</span>
                    </div>
                    <h1 className="text-6xl md:text-8xl font-black tracking-tighter uppercase leading-[0.85] mb-8">
                        HOW CAN WE <br />
                        <span className="gold-gradient">HELP YOU?</span>
                    </h1>
                    <p className="text-xl text-zinc-400 max-w-2xl mx-auto leading-relaxed font-medium">
                        Search our knowledge base for institutional trading answers, security protocols, and platform guidance.
                    </p>
                </div>
            </section>

            {/* FAQ Content */}
            <section className="py-20 px-6">
                <div className="max-w-4xl mx-auto space-y-16">
                    {faqs.map((cat, idx) => (
                        <div key={idx} className="space-y-6">
                            <h2 className="text-2xl font-black uppercase tracking-widest text-brand-gold border-l-4 border-brand-gold pl-6">
                                {cat.category}
                            </h2>
                            <div className="space-y-4">
                                {cat.questions.map((faq, fidx) => (
                                    <FAQItem key={fidx} question={faq.q} answer={faq.a} />
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            {/* CTA Section */}
            <section className="py-20 px-6">
                <div className="max-w-4xl mx-auto glass p-12 rounded-[40px] border-white/5 text-center space-y-8">
                    <Zap size={40} className="text-brand-gold mx-auto" />
                    <h3 className="text-3xl font-black uppercase tracking-tight">Still have questions?</h3>
                    <p className="text-zinc-500 font-medium">Our account managers are available 24/7 to assist with institutional trades and technical support via WhatsApp.</p>
                    <a 
                        href="/dashboard/support"
                        className="inline-block px-10 py-4 bg-brand-gold text-black rounded-2xl font-black uppercase tracking-widest hover:scale-105 active:scale-95 transition-all shadow-2xl shadow-brand-gold/20"
                    >
                        Contact Manager
                    </a>
                </div>
            </section>

            <Footer />
        </div>
    );
}

function FAQItem({ question, answer }: { question: string, answer: string }) {
    return (
        <div className="glass p-8 rounded-[32px] border-white/5 hover:border-white/10 transition-all group">
            <h4 className="text-lg font-black tracking-tight mb-4 group-hover:text-brand-gold transition-colors">{question}</h4>
            <p className="text-zinc-400 font-medium leading-relaxed">{answer}</p>
        </div>
    );
}
